// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/AdminLayout.vue')['default']
    ButtonRepo: typeof import('./src/components/ButtonRepo.vue')['default']
    FileUpload: typeof import('./src/components/FileUpload.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    TicketForm: typeof import('./src/components/TicketForm.vue')['default']
  }
}
